apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- base/argocd.yaml
- base/argocd-apps.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.1/manifests/install.yaml

patches:
- path: overlays/argocd-server-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1
    