apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: argocd/apps
    repoURL: https://github.com/amirmarmul/argocd-guide.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true