apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    chart: argocd-apps
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.0.0
    helm:
      valuesObject:
      {{- with .Values.apps }}
        applications:
        {{- toYaml . | nindent 10 }}
      {{ end }}
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
