apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  sources:
  - chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.4.4
    helm: 
      valueFiles:
      - $values/argocd.yaml
  - path: argocd/base/values
    ref: values
    repoURL: https://github.com/amirmarmul/argocd-guide.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
