apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: argocd/base
    repoURL: https://github.com/amirmarmul/argocd-guide.git
    targetRevision: HEAD
