apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom
spec:
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: custom
        image: docker.io/kacestudio/custom:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
