apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: argocd/apps/nginx
    repoURL: https://github.com/amirmarmul/argocd-guide.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true