apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  source:
    path: argocd/apps
    repoURL: https://github.com/amirmarmul/argocd-guide.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true