apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    chart: argocd-apps
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
