apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    chart: argocd-image-updater
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.11.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true